name: build-frontend-action
'on': push
jobs:
  build:
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build
