name: build-frontend-action
on: push
defaults:
  run:
    working-directory: frontend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: list files
        run: ls
      - name: build
        run: npm run build
